# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd9df642f0918a7a61ce6208f8221eb07cd90400053598f9cfa9cfab59506ba772b66dbcf67cb82b7cfa71b6af4c789de41cdca3f8635ddbbe269f82ed9a18c9

test:
  secret_key_base: 4e578554f039757baab31c2e6b1928d768d499de5cc42570f8489452fe642f685a7f5a9f225319e53945f18d2352eef608c2976ff80464dd7c310b1beb4c28a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
